### ISSUE TITLE
Sprint Prep: Content for Registration form for Cori

### ISSUE THREAD

**Issue by charise** [SFDO-Community-Sprints/NPSP-Videography#135]

**Comment by coriobriensfdo** [comment]
@barbarachristensen just FYI I have the reg page all ready to go, just waiting on the task list. Thanks for sending out a save the date btw!

**Comment by barbarachristensen** [comment]
@coriobriensfdo -- here you go! @charise yell if you have any updates. 

- Collaborate with other sprinters to identify the NPSP features that most need videos
- Dive deep on features with scripts currently in progress, including Gift Entry, Program Management Module, and Enhanced Recurring Donations
- Review in-progress scripts for accuracy, tone, and flow by following along and comparing to NPSP documentation
- Record audio narration for in-progress scripts (you just need a decent internet connection and headset with a mic)
- Translate existing scripts into [many languages](url) for users all over the world

**Comment by coriobriensfdo** [comment]
Done! I'll dm you so you can test the live link before we share.
