### ISSUE TITLE
Give BRC & Bill access to the PMM ERD (share didn't work)

### ISSUE THREAD

**Issue by barbarachristensen** [SFDO-Community-Sprints/NPSP-Videography#137]
Can you please reshare that PMM ERD copy-- it says "you have to be a member of the account" to open it as is. Thanks!

**Comment by coriobriensfdo** [comment]
> Can you please reshare that PMM ERD copy-- it says "you have to be a member of the account" to open it as is. Thanks!

hmmmmm it allowed me to share it with you regardless of you being outside of SF, however perhaps it's locked down from an account perspective. I can't give you access to our account so not sure this will work afterall. I'm happy to download it into a PDF in that case, but it would mean re-creating it on your end. It's not massive though... Let me know what you think.
