### ISSUE TITLE
Ask Salesforce about Recurring Gifts PDF

### ISSUE THREAD

**Issue by charise** [SFDO-Community-Sprints/NPSP-Videography#5]
Check in with Melissa B on why Recurring Gifts is still in a PDF - is it up to date and any risk of wasting anything if we don’t wait until it’s part of website?

**Comment by coriobriensfdo** [comment]
@charise just a heads up that the doc is being changed from PDF to web pages in the next few weeks! I don't think the content should change much as the PDF is kept up to date regularly, so you should be good to go!

**Comment by charise** [comment]
https://powerofus.force.com/s/article/NPSP-Recurring-Donations-Overview-and-Setup
