### ISSUE TITLE
PMM: Install PMM

### ISSUE THREAD

**Issue by Billflorio** [SFDO-Community-Sprints/NPSP-Videography#84]
https://docs.google.com/document/d/1eiK6xA7eqYmYC3sPg2FNDeHEgHiFOG6c57lkVUeKbl8/edit

https://powerofus.force.com/s/article/PMM-Install

**Comment by pkasolves** [comment]
We made inline edits and resolved all comments but one. @barbarachristensen could you check on the final comment and make a call on this one?

**Comment by barbarachristensen** [comment]
@coriobriensfdo  this is cleaned up and ready for you!

**Comment by coriobriensfdo** [comment]
> @coriobriensfdo this is cleaned up and ready for you!

Looks great...back to you! :)

**Comment by mbaizman** [comment]
@Billflorio want me to voice record this?
